a = {
    "name": "None.Reporter",
    "app": None,
    "table": "re_port_er",
    "abstract": False,
    "description": "Whom is assigned as the reporter ",
    "docstring": "Whom is assigned as the reporter ",
    "unique_together": [],
    "pk_field": {
        "name": "id",
        "field_type": "IntField",
        "db_column": "id",
        "python_type": "int",
        "generated": True,
        "nullable": False,
        "unique": True,
        "indexed": True,
        "default": None,
        "description": None,
        "docstring": None,
        "constraints": {"ge": 1, "le": 2147483647},
        "db_field_types": {"": "INT"},
    },
    "data_fields": [
        {
            "name": "name",
            "field_type": "TextField",
            "db_column": "name",
            "python_type": "str",
            "generated": False,
            "nullable": False,
            "unique": False,
            "indexed": False,
            "default": None,
            "description": None,
            "docstring": None,
            "constraints": {},
            "db_field_types": {"": "TEXT", "mysql": "LONGTEXT"},
        }
    ],
    "fk_fields": [],
    "backward_fk_fields": [],
    "o2o_fields": [],
    "backward_o2o_fields": [],
    "m2m_fields": [],
}
b = {
    "name": "fast_tmp.Tree",
    "app": "fast_tmp",
    "table": "tree",
    "abstract": False,
    "description": None,
    "docstring": None,
    "unique_together": [],
    "pk_field": {
        "name": "id",
        "field_type": "IntField",
        "db_column": "id",
        "python_type": "int",
        "generated": True,
        "nullable": False,
        "unique": True,
        "indexed": True,
        "default": None,
        "description": None,
        "docstring": None,
        "constraints": {"ge": 1, "le": 2147483647},
        "db_field_types": {"": "INT"},
    },
    "data_fields": [
        {
            "name": "parent_id",
            "field_type": "IntField",
            "db_column": "parent_id",
            "python_type": "int",
            "generated": False,
            "nullable": False,
            "unique": False,
            "indexed": False,
            "default": None,
            "description": None,
            "docstring": None,
            "constraints": {"ge": 1, "le": 2147483647},
            "db_field_types": {"": "INT"},
        },
        {
            "name": "child_id",
            "field_type": "IntField",
            "db_column": "child_id",
            "python_type": "int",
            "generated": False,
            "nullable": False,
            "unique": False,
            "indexed": False,
            "default": None,
            "description": None,
            "docstring": None,
            "constraints": {"ge": 1, "le": 2147483647},
            "db_field_types": {"": "INT"},
        },
    ],
    "fk_fields": [
        {
            "name": "parent",
            "field_type": "ForeignKeyFieldInstance",
            "python_type": "fast_tmp.Node",
            "generated": False,
            "nullable": False,
            "unique": False,
            "indexed": False,
            "default": None,
            "description": None,
            "docstring": None,
            "constraints": {},
            "raw_field": "parent_id",
            "on_delete": "CASCADE",
            "table": "node",
        },
        {
            "name": "child",
            "field_type": "ForeignKeyFieldInstance",
            "python_type": "fast_tmp.Node",
            "generated": False,
            "nullable": False,
            "unique": False,
            "indexed": False,
            "default": None,
            "description": None,
            "docstring": None,
            "constraints": {},
            "raw_field": "child_id",
            "on_delete": "CASCADE",
            "table": "node",
        },
    ],
    "backward_fk_fields": [],
    "o2o_fields": [],
    "backward_o2o_fields": [],
    "m2m_fields": [],
}
